// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwuLQlZRAo_UlvMWYnsRVpL5NT5g8m5mg',
    appId: '1:525737623263:web:7c9a6f000df0ed3e75336a',
    messagingSenderId: '525737623263',
    projectId: 'bb-clean-c2dad',
    authDomain: 'bb-clean-c2dad.firebaseapp.com',
    storageBucket: 'bb-clean-c2dad.appspot.com',
    measurementId: 'G-S5K3W0K4YN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtGjDwq5_90dEwNcO3dFTinrAQp2-aacE',
    appId: '1:525737623263:android:0edf17cd17a9658975336a',
    messagingSenderId: '525737623263',
    projectId: 'bb-clean-c2dad',
    storageBucket: 'bb-clean-c2dad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDluIzLE_hjyo_Cq8h3BZ7SzfJ702IVpx0',
    appId: '1:525737623263:ios:6df9747c48dd019775336a',
    messagingSenderId: '525737623263',
    projectId: 'bb-clean-c2dad',
    storageBucket: 'bb-clean-c2dad.appspot.com',
    iosClientId: '525737623263-6a1k6gsdups6bvlgv1d393pimosceqbq.apps.googleusercontent.com',
    iosBundleId: 'com.example.superclean',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDluIzLE_hjyo_Cq8h3BZ7SzfJ702IVpx0',
    appId: '1:525737623263:ios:6df9747c48dd019775336a',
    messagingSenderId: '525737623263',
    projectId: 'bb-clean-c2dad',
    storageBucket: 'bb-clean-c2dad.appspot.com',
    iosClientId: '525737623263-6a1k6gsdups6bvlgv1d393pimosceqbq.apps.googleusercontent.com',
    iosBundleId: 'com.example.superclean',
  );
}
